include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = DuoBarPrefs
DuoBarPrefs_FILES = DuoBarPrefsListController.m DuoSliderCell.m
DuoBarPrefs_INSTALL_PATH = /Library/PreferenceBundles
DuoBarPrefs_FRAMEWORKS = UIKit
DuoBarPrefs_PRIVATE_FRAMEWORKS = Preferences
DuoBarPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
